Develop v1.3
OrientCue/RSSReader pull request #4
Opened 2021-02-03 13:19 UTC by OrientCue

# v.1.3. Autodiscovery and Settings
- App will be able to autodiscover feeds from any web site and will allow user to select a feed that he wants
- App will create a settings file in its Documents folder where it will save the users choice and use it later in the app
- App should have a view where user can reconfigure the feed URL (either by typing it or by autodiscovering it from a web site)

Example: load `http://tut.by` and view source.
It will have several <link> tags in header that will point to different rss feeds like:
```html 
<link rel="alternate" type="application/rss+xml" title="TUT.BY - Все новости за день" href="http://news.tut.by/rss/all.rss" />
```

2021-02-16 08:29 UTC, AndreiChernyshou requested changes
fix the comments, please

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Presenter/ChannelsPresenter/ChannelsPresenter.m
> +    _service = ChannelsLocalStorageService.shared;
The dependence should be injected. Otherwise it is hidden and not evident.

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Presenter/ChannelsPresenter/ChannelsPresenter.m
> +  [self.view displayFeedForChannels:store.channels selected:store.selectedChannel];
Will you proceed even after an error happens? Is it expected behaviour?

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Presenter/ChannelsPresenter/ChannelsPresenter.m
> +  [self.view update:store.channels selected:store.selectedChannel];
The same is here

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Presenter/SearchChannelsPresenter/SearchChannelsPresenter.m
> +    _localStorage = ChannelsLocalStorageService.shared;
Storage should be injected

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Presenter/SearchChannelsPresenter/SearchChannelsPresenter.m
> +  [channels enumerateObjectsUsingBlock:^(RSSChannel *obj, NSUInteger idx, BOOL *stop) {
What for do you use block enumeration? You don't use stop param. Use just for in loop in this case.

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Presenter/SearchChannelsPresenterTypes/SearchChannelsPresenterType.h
> +@property (nonatomic, assign) id<SearchChannelsViewType> view;
assign with reference type.

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/AutodiscoveryHTMLParser/AutodiscoveryHTMLParser.m
> +- (NSArray<NSDictionary<NSString *, NSString *> *> *)parseHTML:(NSData *)data {
What's wrong with your indentation?

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/AutodiscoveryHTMLParser/AutodiscoveryHTMLParser.m
> +- (NSDictionary *)channelFromLinkTag:(NSString *)string {
indentation

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/AutodiscoveryHTMLParser/AutodiscoveryHTMLParser.m
> +- (NSString *)valueForTagEntry:(NSString *)tag inString:(NSString *)string {
indentation

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/AutodiscoveryRSS.m
> +    _validator = [URLValidator new];
This should be done inside getter

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/RSSChannelParser.m
> +- (void)parser:(NSXMLParser *)parser
5 parameters are too much. This code smells

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/URLValidator.m
> +NSString *const kRRSiteValidatorErrorNilSite = @"Attempt to validate nil site argument.";
These should be added to localised keys

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/URLValidator.m
> +  if (!site) {
What for do use nesting here? That complicates reading!
if (!site && error) {
    *error = [self errorNilString];
     return nil;
   }

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/URLValidator.m
> +  if (url.scheme && url.host) {
the same

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/URLValidator.m
> +  if (!url.scheme && !url.host && url.path) {
3 level nesting. Common! Do you really need it?

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/URLValidator.m
> +  if (!link) {
the same

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/URLValidator.m
> +  if (!link.length) {
the same

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/URLValidator.m
> +    if (error) { *error = [self errorCantFormURL]; }
you are always duplicating a call '*error = [self errorCantFormURL];'
Do it once at the very top and return nil or result in all other places. That will allow you to escape from nesting everywhere within the scope.

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/ChannelsLocalStorageService/ChannelsLocalStorageService.m
> +
What for do you need an empty override?

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/ChannelsLocalStorageService/ChannelsLocalStorageService.m
> +  return error && *error ? false : true;
just !error && !*error

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/ChannelsLocalStorageService/ChannelsLocalStorageService.m
> +  return error && *error ? false : true;
the same here and in other places.

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/FeedNetworkService/FeedNetworkService.m
> +    _queue = [NSOperationQueue new];
Queue should be created in getter

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/ViewControllers/ChannelsViewController/ChannelsViewController.m
> +    _presenter.view = self;
Check for a memory leak here.

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/ViewControllers/ChannelsViewController/ChannelsViewController.m
> +  if (selected >= 0 && selected < self.channels.count && self.channels) {
this check smells

2021-02-16 08:29 UTC, AndreiChernyshou commented on RSSReader/RSSReader/ViewControllers/SearchChannelsController/SearchChannelsController.m
> +- (UIBarButtonItem *)cancelBarButton {
Just create a button with block init for it and stop using selector)

2021-02-16 09:33 UTC, OrientCue commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/RSSChannelParser.m
> +- (void)parser:(NSXMLParser *)parser
Apple's NSXMLParserDelegate protocol method.
Fixed.

2021-02-16 09:37 UTC, OrientCue commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/AutodiscoveryHTMLParser/AutodiscoveryHTMLParser.m
> +- (NSArray<NSDictionary<NSString *, NSString *> *> *)parseHTML:(NSData *)data {
What are exact requirements for indentation? 4 spaces?

2021-02-16 09:54 UTC, OrientCue commented on RSSReader/RSSReader/ViewControllers/SearchChannelsController/SearchChannelsController.m
> +- (UIBarButtonItem *)cancelBarButton {
What initialiser should I use to pass block as action? Can't find any for UIBarButtonItem.

2021-02-16 09:57 UTC, OrientCue commented on RSSReader/RSSReader/ViewControllers/ChannelsViewController/ChannelsViewController.m
> +    _presenter.view = self;
Inside presenter view is weak referenced:
```objc
@protocol ChannelsPresenterType <NSObject>
@property (nonatomic, assign) id<ChannelsViewType> view;
...
```
Thus there is no reference cycle.

2021-02-16 16:12 UTC, OrientCue commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/URLValidator.m
> +  if (!site) {
```objc
if (!site && error) {
    *error = [self errorNilString];
    return nil;
}
```
In this case I should assume that error is not nil. If it is nil - I will fall through 'if' body and early return from function will not happen.

2021-02-16 16:18 UTC, OrientCue commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/URLValidator.m
> +    if (error) { *error = [self errorCantFormURL]; }
There is no duplication call inside this method, I assign to error variable three different types of error.

2021-02-16 16:21 UTC, OrientCue commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/URLValidator.m
> +    if (error) { *error = [self errorCantFormURL]; }
> Do it once at the very top and return nil or result in all other places.
In this case error will be assigned and if caller handle errors it will display error in any case.

2021-02-16 16:25 UTC, OrientCue commented on RSSReader/RSSReader/Services/ChannelsLocalStorageService/ChannelsLocalStorageService.m
> +
This empty override prevents accidentally deallocating of shared instance.

2021-02-16 16:35 UTC, OrientCue commented on RSSReader/RSSReader/Services/ChannelsLocalStorageService/ChannelsLocalStorageService.m
> +  return error && *error ? false : true;
fixed

2021-02-16 16:35 UTC, OrientCue commented on RSSReader/RSSReader/Services/ChannelsLocalStorageService/ChannelsLocalStorageService.m
> +  return error && *error ? false : true;
fixed

2021-02-16 16:53 UTC, OrientCue commented on RSSReader/RSSReader/Services/FeedNetworkService/FeedNetworkService.m
> +    _queue = [NSOperationQueue new];
fixed

2021-02-16 20:11 UTC, OrientCue commented on RSSReader/RSSReader/Presenter/SearchChannelsPresenter/SearchChannelsPresenter.m
> +  [channels enumerateObjectsUsingBlock:^(RSSChannel *obj, NSUInteger idx, BOOL *stop) {
fixed

2021-02-16 20:15 UTC, OrientCue commented on RSSReader/RSSReader/Presenter/SearchChannelsPresenter/SearchChannelsPresenter.m
> +    _localStorage = ChannelsLocalStorageService.shared;
fixed

2021-02-16 20:16 UTC, OrientCue commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/AutodiscoveryRSS.m
> +    _validator = [URLValidator new];
fixed

2021-02-16 20:24 UTC, OrientCue commented on RSSReader/RSSReader/Presenter/ChannelsPresenter/ChannelsPresenter.m
> +    _service = ChannelsLocalStorageService.shared;
fixed

2021-02-16 20:25 UTC, OrientCue commented on RSSReader/RSSReader/Presenter/ChannelsPresenter/ChannelsPresenter.m
> +  [self.view displayFeedForChannels:store.channels selected:store.selectedChannel];
fixed

2021-02-16 20:25 UTC, OrientCue commented on RSSReader/RSSReader/Presenter/ChannelsPresenter/ChannelsPresenter.m
> +  [self.view update:store.channels selected:store.selectedChannel];
fixed

2021-02-17 12:33 UTC, OrientCue commented on RSSReader/RSSReader/Presenter/SearchChannelsPresenterTypes/SearchChannelsPresenterType.h
> +@property (nonatomic, assign) id<SearchChannelsViewType> view;
View has strong reference to presenter, presenter holds weak reference to view. This will avoid reference cycle between view and presenter.

2021-02-17 12:39 UTC, OrientCue commented on RSSReader/RSSReader/ViewControllers/SearchChannelsController/SearchChannelsController.m
> +- (UIBarButtonItem *)cancelBarButton {
It is possible to pass block as a target and use invoke selector. For this approach I should retain somewhere passed block.

2021-02-17 12:41 UTC, OrientCue commented on RSSReader/RSSReader/Coordinators/SplitCoordinator/SplitCoordinator.m
> +- (void)displayError:(NSError *)error {
I delegate all calls of displayError to SplitCoordinator.

2021-02-17 12:52 UTC, OrientCue commented on RSSReader/RSSReader/Coordinators/ChannelsCoordinator/ChannelsCoordinator.h
> +@property (nonatomic, assign, readonly) UIViewController<ChannelsViewType> *channelsViewController;
Here channelsViewController will be retained by splitViewController. This weak reference allows channelViewController to be deallocated, when it removed from splitViewController. Also this approach avoid potential reference cycle.

2021-02-17 12:54 UTC, OrientCue commented on RSSReader/RSSReader/Coordinators/ChannelsCoordinator/ChannelsCoordinator.m
> +@property (nonatomic, assign) UINavigationController *navigationController;
This weak reference was intended to avoid potential memory leak.

2021-02-19 12:39 UTC, OrientCue commented on RSSReader/RSSReader/Coordinators/ChannelsCoordinator/ChannelsCoordinator.h
> +@property (nonatomic, assign, readonly) UIViewController<ChannelsViewType> *channelsViewController;
fixed to retain attribute

2021-02-19 12:40 UTC, OrientCue commented on RSSReader/RSSReader/Coordinators/ChannelsCoordinator/ChannelsCoordinator.m
> +@property (nonatomic, assign) UINavigationController *navigationController;
fixed

2021-02-19 12:40 UTC, OrientCue commented on RSSReader/RSSReader/Coordinators/ChannelsCoordinator/ChannelsCoordinator.m
> +  ChannelsCoordinator *coordinator = [ChannelsCoordinator new];
fixed

2021-02-19 12:40 UTC, OrientCue commented on RSSReader/RSSReader/Coordinators/FeedCoordinator/FeedCoordinator.h
> +@property (nonatomic, assign, readonly) UIViewController<FeedViewType> *feedController;
fixed

2021-02-19 12:40 UTC, OrientCue commented on RSSReader/RSSReader/Coordinators/SplitCoordinator/SplitCoordinator.m
> +  SplitCoordinator *coordinator = [SplitCoordinator new];
fixed

2021-02-19 12:40 UTC, OrientCue commented on RSSReader/RSSReader/Coordinators/SplitCoordinator/SplitCoordinator.m
> +- (void)launch {
fixed

2021-02-19 12:41 UTC, OrientCue commented on RSSReader/RSSReader/Coordinators/SplitCoordinator/SplitCoordinator.m
> +- (void)displayError:(NSError *)error {
fixed

2021-02-20 09:05 UTC, OrientCue commented on RSSReader/RSSReader/ViewControllers/ChannelsViewController/ChannelsViewController.m
> +  if (selected >= 0 && selected < self.channels.count && self.channels) {
fixed

2021-02-21 11:58 UTC, OrientCue commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/URLValidator.m
> +NSString *const kRRSiteValidatorErrorNilSite = @"Attempt to validate nil site argument.";
Fixed. I use this strings as a keys for NSLocalizedString.

2021-02-22 10:09 UTC, AndreiChernyshou requested changes
Please, check comments

2021-02-22 10:09 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/ChannelsLocalStorageService/ChannelsLocalStorageService.m
> +
What do you mean under accidental reallocation? Deallocation happens based on the value of reference counter. The implementation provided might lead to a leak

2021-02-22 10:09 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/ChannelsLocalStorageService/ChannelsLocalStorageService.m
> +    return nil;
Why don't you handle errors here?

2021-02-22 10:09 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Services/ChannelsLocalStorageService/ChannelsLocalStorageService.m
> +  return error && *error ? false : true;
just 
return !( error && *error)

2021-02-22 18:15 UTC, OrientCue commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/AutodiscoveryHTMLParser/AutodiscoveryHTMLParser.m
> +- (NSArray<NSDictionary<NSString *, NSString *> *> *)parseHTML:(NSData *)data {
fixed

2021-02-22 18:16 UTC, OrientCue commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/AutodiscoveryHTMLParser/AutodiscoveryHTMLParser.m
> +- (NSDictionary *)channelFromLinkTag:(NSString *)string {
fixed

2021-02-22 18:16 UTC, OrientCue commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/AutodiscoveryHTMLParser/AutodiscoveryHTMLParser.m
> +- (NSString *)valueForTagEntry:(NSString *)tag inString:(NSString *)string {
fixed

2021-02-22 20:12 UTC, OrientCue commented on RSSReader/RSSReader/Services/ChannelsLocalStorageService/ChannelsLocalStorageService.m
> +    return nil;
Caller of this method handles error:
```objc
/// ChannelsPresenter
- (void)loadFromLocalStorage {
    NSError *error = nil;
    SettingsStore *store = [self.service loadSavedStoreError:&error]; // this method call
    if (error) {
        [self.view displayError:error];
    } else {
        [self.view displayFeedForChannels:store.channels selected:store.selectedChannel];
    }
}
```

2021-02-22 20:15 UTC, OrientCue commented on RSSReader/RSSReader/Presenter/SearchChannelsPresenter/SearchChannelsPresenter.m
> +  NSMutableIndexSet *alreadyAdded = [NSMutableIndexSet indexSet];
fixed

2021-02-22 20:26 UTC, OrientCue commented on RSSReader/RSSReader/Services/ChannelsLocalStorageService/ChannelsLocalStorageService.m
> +  return error && *error ? false : true;
Nice! Thanks.
Fixed.

2021-02-22 20:27 UTC, OrientCue commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/AutodiscoveryRSS.m
> +  if (error) {
Fixed.

2021-02-22 20:27 UTC, OrientCue commented on RSSReader/RSSReader/Services/AutodiscoveryRSS/AutodiscoveryRSS.m
> +    if (weakOperation.error) {
fixed

2021-02-22 20:33 UTC, OrientCue commented on RSSReader/RSSReader/ViewControllers/SearchChannelsController/SearchChannelsController.m
> +- (UIBarButtonItem *)cancelBarButton {
Fixed

2021-02-22 20:34 UTC, OrientCue commented on RSSReader/RSSReader/Services/ChannelsLocalStorageService/ChannelsLocalStorageService.m
> +  return error && *error ? false : true;
fixed

2021-02-23 13:50 UTC, AndreiChernyshou requested changes

2021-02-23 13:50 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Coordinators/FeedCoordinator/FeedCoordinator.m
> +    __block typeof(self) weakSelf = self;
What for do you need a __block modifier here?

2021-02-23 13:50 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Helpers/UIAlertController+Alert/UIAlertController+RRErrorAlert.m
> +    __weak typeof(self) weakSelf = self;
The same

2021-02-23 13:50 UTC, AndreiChernyshou commented on RSSReader/RSSReader/Helpers/UIBarButtonItem+ASBlockInit/UIBarButtonItem+ASBlockInit.m
> +    if (self = [self initWithBarButtonSystemItem:systemItem
That is a working approach but I wonder why didn't you inherit from basic class and add another property and custom init this way?

2021-02-23 14:31 UTC, OrientCue commented on RSSReader/RSSReader/Coordinators/FeedCoordinator/FeedCoordinator.m
> +    __block typeof(self) weakSelf = self;
I use here __block modifier for weakify reference to self under MRC.

2021-02-23 14:48 UTC, OrientCue commented on RSSReader/RSSReader/Helpers/UIAlertController+Alert/UIAlertController+RRErrorAlert.m
> +    __weak typeof(self) weakSelf = self;
Here dispatch_after will capture `self`. I think alert should be deallocated after it was dismissed. (For example by tap on OK button.) If I use `__block` modifier it will lead to crash. I decided to use `__weak` modifier under MRC because it provide safest behaviour.

2021-02-23 14:53 UTC, OrientCue commented on RSSReader/RSSReader/Helpers/UIBarButtonItem+ASBlockInit/UIBarButtonItem+ASBlockInit.m
> +    if (self = [self initWithBarButtonSystemItem:systemItem
That is sort of category and associated object usage.

2021-02-23 19:13 UTC, AndreiChernyshou approved these changes

2021-02-26 17:03 UTC, merged